"""Add RSVP model and event_type to Event model

Revision ID: f39178f4ae6d
Revises:
Create Date: 2025-07-01 20:19:17.671505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f39178f4ae6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bags_games',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team1_players', sa.JSON(), nullable=False),
    sa.Column('team2_players', sa.JSON(), nullable=False),
    sa.Column('team1_score', sa.Integer(), nullable=False),
    sa.Column('team2_score', sa.Integer(), nullable=False),
    sa.Column('winning_team', sa.Integer(), nullable=True),
    sa.Column('game_type', sa.String(length=20), nullable=True),
    sa.Column('tournament_id', sa.String(length=36), nullable=True),
    sa.Column('tournament_round', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('favorite_band', sa.String(length=100), nullable=True),
    sa.Column('beach_member_since', sa.Date(), nullable=True),
    sa.Column('bags_wins', sa.Integer(), nullable=True),
    sa.Column('bags_losses', sa.Integer(), nullable=True),
    sa.Column('bags_tournament_wins', sa.Integer(), nullable=True),
    sa.Column('events_created', sa.Integer(), nullable=True),
    sa.Column('sasquatch_sightings', sa.Integer(), nullable=True),
    sa.Column('notify_events', sa.Boolean(), nullable=True),
    sa.Column('notify_bags_games', sa.Boolean(), nullable=True),
    sa.Column('notify_messages', sa.Boolean(), nullable=True),
    sa.Column('google_id', sa.String(length=100), nullable=True),
    sa.Column('google_picture_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('bags_tournaments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tournament_type', sa.Integer(), nullable=False),
    sa.Column('players', sa.JSON(), nullable=False),
    sa.Column('bracket', sa.JSON(), nullable=True),
    sa.Column('champion_id', sa.String(length=36), nullable=True),
    sa.Column('champion_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('current_round', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rsvps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_id', name='uq_user_event_rsvp')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rsvps')
    op.drop_table('events')
    op.drop_table('bags_tournaments')
    op.drop_table('users')
    op.drop_table('bags_games')
    # ### end Alembic commands ###
